### ISSUE TITLE
How to use the different fingerprint files for all the streams

### ISSUE THREAD

**Issue by RodolpheFouquet** [cta-wave/Test-Content-Generation#11]
On the Wiki, here, you can see that we need to generated 15 different streams https://github.com/cta-wave/Test-Content-Generation/wiki/AVC-test-streams

However, here, on the [Mezzanine](http://dash.akamaized.net/WAVE/Mezzanine), we have only 1 to 3 versions of ToS or Croatia for every resolution.

I don,t really understand how the mapping should be done here.

**Comment by jpiesing** [comment]
Does this help ....

We need to ensure that each test stream is run at least once and that each test program has the right streams to run.
- Some test streams will only be used once with one test program (e.g. the test program for simple linear playback from beginning to end) because that's enough to test that a particular content option works. 
- Some test streams will be used with more than one test program - because that's what the various test programs needs
- Some test programs will only need to be run once with one test stream or set of test streams
- Some test programs will need to be run more than once in order to ensure all test streams are played

Some mezzanine streams will be encoded / packaged more than once in order to derive more than one test stream from them,

You could consider it a sparse matrix but I suspect that a number of test streams (most?) will only be used with one test program.

@nicholas-fr  Does this match your understanding?

**Comment by RodolpheFouquet** [comment]
Understood

**Comment by nicholas-fr** [comment]
@jpiesing  That matches my understanding. 

We have mezzanine streams for all the resolutions to be tested.
The mezzanine streams enable use of a unique label for each different track within a given CMAF switching set, used for a given test. 
Up to 3 label variants for some mezzanine resolutions are there for tests requiring multiple video tracks that vary other than by resolution.
