### ISSUE TITLE
Available content options

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/Test-Content-Generation#6]
Check what content options can be produced with FFMPEG

**Comment by jpiesing** [comment]
Here is the list of content options which have been mentioned;
- with and without picture timing SEI message
- with and without VUI timing information
- Sample entry, see CMAF clause 9.4.1.2; 3 options;
1. avc1 sample entry type (parameter sets within the CMAF Header)
2. avc3 sample entry type (in-band parameter sets) without parameter sets within the CMAF header
3. avc3 sample entry type (in-band parameter sets) with parameter sets within the CMAF header
- CMAF Fragment durations (e.g. 2s or 5s)
- Initialization Constraints, either
1. Regular Switching Set, do not apply CMAF clause 7.3.4.2 and 9.2.11.4 or
2. Single initialization constraints, see CMAF clause 7.3.4.2 and 9.2.11.4
- Fragments containing one or multiple moof/mdat pairs [reference to Media profile spec]
1. Fragment is 1 chunk
2. Fragment contains multiple chunks (p-frame to p-frame with b-frames)
3. Each sample constitutes a chunk (p-frame only)
- emsg box (v0 and v1)
- negative composition time offset.
- undefined ISOBMFF boxes
- playlists

**Comment by haudiobe** [comment]
The content options are documented in the wiki page for each Profile. The available content options are documented. We may move this documentation back to the code creating markdown pages.

**Comment by jpiesing** [comment]
Ideally someone would take a list of content options, cross-reference this against ffmpeg to see which ones could be generated, generate an example of each and cross-check with stream analysis tools that the option is generated 1) as we would expect and 2) according to the specifications.

**Comment by haudiobe** [comment]
Feedback from @eceozturk 

I have not done the complete check but some features that I know are as follows:
- Sample entry avc1 is supported but not avc3. When specifying the encoder in the ffmpeg command (“libx264” can be searched in the source code), directly avc1 is used. (Representation class in the code.)
- VUI information is optional. This can be provided with “color_primaries”, “color_trc” and “colorspace” options. (Representation class in the code.)
- Fragment durations can be configured in the DASH class with seg_duration option. I do not know for the chunking but for this min_keyint, key_int, seg_duration options could be relevant.

Please let me know if any issues.

**Comment by jamrial** [comment]
avc3 is supported by using the tag option and avc3 as argument, otherwise avc1 is used. The presence of in-band parameter sets depends on the output of the encoder, but there are bitstream filters available that remove or inject them if needed (dump_extradata and remove_extradata).

Fragmentation is handled by the frag_type, frag_duration and seg_duration dash muxer options as follows:
one chunk per segment -> frag_type none
p-frame to p-frame with b-frames -> frag_type pframes
each sample constitutes a chunk -> frag_type every_frame
arbitrary duration -> frag_type duration, combined with a value in seconds for frag_duration and/or seg_duration (the former must be smaller than the latter for obvious reasons), and min_keyint and key_int parameters for the encoder. Timebase/framerate plus the keyint values must be taken into consideration when choosing the duration value.

negative composition time offset can be enabled with the negative_cts_offsets flag passed to the movflags option from the mp4 muxer (from within the dash muxer, this is done with the format_options option). Alternatively, the cmaf flag for movflags, which enables negative cts offsets plus a few other considerations.

**Comment by haudiobe** [comment]
DPCTF 2020/07/29: add the above parameters to the script

**Comment by rbouqueau** [comment]
Can this issue be closed? FYI here is the table of implemented parameters: ```Stream ID , picture timing SEI message , VUI timing information , Sample entry (CMAF 9.4.1.2) , Sample entry (CMAF 9.4.1.2) in header , CMAF fragment duration in seconds, Initialization constraints ,frag_type```

**Comment by jpiesing** [comment]
I think this issue can be closed.
@haudiobe as the original proposer, do you agree?
